# Start Homebrew Releaser when a new GitHub release is created

---
name: Release to Homebrew

"on":
  release:
    types: [published]

jobs:

  homebrew-releaser:
    runs-on: ubuntu-latest
    name: homebrew-releaser
    # if: "!github.event.release.prerelease"

    steps:
      - name: Calculate expected version output
        id: bin_version
        run: |
          TAG=${{ github.event.release.tag_name }}
          echo "BIN_VERSION=${TAG#v}" >> $GITHUB_OUTPUT
      - run: 'echo version: ${{ steps.bin_version.outputs.BIN_VERSION }}'

      - name: Release to cdzombak/oss tap
        uses: Justintime50/homebrew-releaser@v1
        with:
          homebrew_owner: cdzombak
          homebrew_tap: homebrew-oss
          formula_folder: formula
          update_readme_table: true
          github_token: ${{ secrets.HOMEBREW_RELEASER_PAT }}
          commit_owner: homebrew-releaser-bot
          commit_email: homebrew-releaser-bot@users.noreply.github.com

          target_darwin_amd64: true
          target_darwin_arm64: true
          target_linux_amd64: true
          target_linux_arm64: true

          install: 'bin.install "dirshard"'
          test: 'assert_match("${{ steps.bin_version.outputs.BIN_VERSION }}", shell_output("dirshard -version"))'
